### ISSUE TITLE
Jmeter 4.0 and 5.0 servers fail to start due to rmi_keystore error

### ISSUE THREAD

**Issue by christiannews** [DevOpsLib/jmeter-docker-k8s#9]
Attempting to build the docker image with apache jmeter 5.0 leads to the following error:

rmi_keystore.jks (No such file or directory)

The local_master container would come up but the server wouldn't start.

I was able to fix this issue by updating user.properties within the master container with the following line:
server.rmi.ssl.disable=true

(I also needed to add an extra line in the dockerfile for installing unzip in order for the build to succeed).

After making these changes I was able to build the dockerfile (but set the jmeter version to 5.3 in the build args in order to use a recent version of jmeter) and then docker-compose up my local image successfully, providing me with a master and server container. I was then able to successfully run my jmx tests from within the master docker container. Perhaps adding these changes to 4.0 and 5.0 will allow the servers to start for those that want to use a newer version of jmeter?

**Comment by subanithak** [comment]
You can use [PodPreset ](https://kubernetes.io/docs/tasks/inject-data-application/podpreset/) concept by following steps

- Define user.properties
```
jmeter.save.saveservice.default_delimiter=\t
jmeter.save.saveservice.print_field_names=true
server.rmi.ssl.disable=true
```

- Create a configmap for user.properties.

```console
$ kubectl create configmap user.properties --from-file=user.properties
```

- Create PodPreset as below 
```yaml
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: jmeter-podpreset
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: distributed-jmeter
   
  volumes: 
    - configMap:
          defaultMode: 420
          name: user.properties
      name: user-properties-vol

  volumeMounts:
    - mountPath: /jmeter/apache-jmeter-5.0/bin/user.properties
      name: user-properties-vol
      subPath: user.properties
```

- Apply PodPreset 
```console
$ kubectl apply -f jmeter-podpreset.yaml
```
